### ISSUE TITLE
Adapt UI to the new GRSciColl data model

### ISSUE THREAD

**Issue by marcos-lg** [gbif/registry-console#563]
The following changes have to be adapted in the UI since some of them are breaking changes:

- [x] These new fields have been added: https://github.com/gbif/registry/issues/552
- [x] Collection geography field renamed: https://github.com/gbif/registry/issues/551 
- [x] Fields that are converted into multivalue fields: https://github.com/gbif/registry/issues/550
- [x] Fields that have been removed (`importantCollectors` hasn't been removed yet and it will be done when the collection descriptors are implemented): https://github.com/gbif/registry/issues/545
- [x] Fields that have been converted into vocabularies (ignore the IdentifierType one): https://github.com/gbif/registry/issues/549 . In the API I use the latest release of the vocabulary just in case, so I think you can do the same, e.g.: http://api.gbif-dev.org/v1/vocabularies/Discipline/concepts/latestRelease . Also see: https://github.com/gbif/registry-console/issues/558
- [x] add button to download entities as latimer core

This is not a priority but I also added the Latimer Core endpoints:
- https://api.gbif-dev.org/v1/grscicoll/institution/latimerCore
- https://api.gbif-dev.org/v1/grscicoll/institution/latimerCore/ab720de9-308a-4aae-afba-74d7f91ca886
- POST and PUT to those endpoints above passing the body in LatimerCore format
- The same for collections

These changes are only available in DEV for the moment and will be deployed to the other environments together with the UI.

**Comment by ManonGros** [comment]
Concerning Latimer Core, when it comes to the UI, for now I think we could do one of the followings:
1. Have a button (on the GRScicoll entry pages and/or on the search result page) which is the API call to access data formatted as Latimer Core. And have one in the registry UI for uploading data as LtC
2. Just have a link to the API that specifies that you can access and upload GRSciColl data formatted as Latimer core.

Maybe for now (and given that it isn't urgent), I vote for number 2.

**Comment by ManonGros** [comment]
See also the issue about addresses: https://github.com/gbif/registry/issues/546

**Comment by ManonGros** [comment]
Thanks @MortenHofft!

For the drop down selection of vocabulary, could there be some visual cue to show that the concepts are nested? Right now, it is the same as the enum drop down list.

Ideally, when I manage to add the definitions to the concepts as well, I would like to show that there are definitions. Maybe some (i) and the definition shown when hovering? (I am not sure what is best here). This part isn't as important as showing that the concepts aren't flat.

**Comment by MortenHofft** [comment]
Is it a feature that is preventing us from going to production? Or is what we have in uat better than prod?

**Comment by ManonGros** [comment]
We can't take it to production because now the values have almost no context.

For example, this is what we have currently on prod where "archeological" is repeated for each sub value.
<img width="668" alt="Screenshot 2024-05-15 at 12 28 21" src="https://github.com/gbif/registry-console/assets/7677271/f961c832-56fc-40f4-a824-9a60b9cf0129">
This is what we have on dev:
<img width="643" alt="Screenshot 2024-05-15 at 12 27 58" src="https://github.com/gbif/registry-console/assets/7677271/62c7bfc3-b306-468b-bb11-fb38571f39a0">
There is "archeological" as its own concept way down below and the context for each sub concept is gone. It looks more confusing than before.

Ideally, we would have something in the drop down that shows the nested aspect of the concepts:

Archeological
 |-> C14
 |-> humain remains
 |-> ...
 
If not, then we should at least have something equivalent to what we have now where the parent concept is displayed for each sub-concept. Something like this:
* Archeological
* Archeological | C14
* Archeological | humain remains
* Archeological | ...

**Comment by ManonGros** [comment]
@MortenHofft For the GRSciColl (hosted) portal, we also need to add the temporal coverage field on collection pages and display the images when provided (the later I couldn't test on dev because there is a bug preventing me to save changes).
Should I log it as a separate issue?

**Comment by MortenHofft** [comment]
Personally I prefer individual issues over mega issues yes. especially when it concerns another project. Hosted portals and registry-console are independent projects/code bases.

**Comment by ManonGros** [comment]
Thanks @MortenHofft ! I logged two issues there: https://github.com/gbif/hosted-portals/issues/287 https://github.com/gbif/hosted-portals/issues/286

**Comment by ManonGros** [comment]
Thanks Morten! That will work for prod
